"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

def rtmpdump_version(): # -> str | bytes | dict[Unknown, Unknown] | Any | Literal[False]:
    ...

class RtmpFD(FileDownloader):
    def real_download(self, filename, info_dict):
        ...
