"""
This type stub file was generated by pyright.
"""

import types

_NO_ATTRIBUTE = ...
_Package = ...
def get_package_info(module): # -> Package:
    ...

class EnhancedModule(types.ModuleType):
    def __bool__(self): # -> Any | Literal[True]:
        ...

    def __getattribute__(self, attr): # -> Any:
        ...



def passthrough_module(parent, child, allowed_attributes=..., *, callback=...): # -> ModuleType:
    """Passthrough parent module into a child module, creating the parent if necessary"""
    ...
