"""
This type stub file was generated by pyright.
"""

class BaseTemplate:
    def __init__(self, template_text, **kwargs) -> None:
        ...

    def set_template_text(self, template_text): # -> None:
        ...

    def render(self, **kwargs):
        ...

    def compile_template(self):
        ...

    @property
    def template(self):
        ...



class StringTemplate(BaseTemplate):
    """
    string.Template based engine.
    """
    def compile_template(self): # -> (__mapping: Mapping[str, object] = ..., **kwds: object) -> str:
        ...

    def render(self, **kwargs):
        ...
