"""
This type stub file was generated by pyright.
"""

from .base import BaseTemplate

class MakoTemplate(BaseTemplate):
    def compile_template(self):
        ...

    def render(self, **kwargs):
        ...
