"""
This type stub file was generated by pyright.
"""

from .brightcove import BrightcoveNewBaseIE

class BandaiChannelIE(BrightcoveNewBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...
