"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class BeatBumpVideoIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class BeatBumpPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
