"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class Kanal2IE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    def get_formats(self, playlist, video_id): # -> list[Unknown]:
        ...
