"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class KickBaseIE(InfoExtractor):
    ...


class KickIE(KickBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class KickVODIE(KickBaseIE):
    _VALID_URL = ...
    _TESTS = ...
