"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class PeekVidsBaseIE(InfoExtractor):
    ...


class PeekVidsIE(PeekVidsBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class PlayVidsIE(PeekVidsBaseIE):
    _VALID_URL = ...
    _TESTS = ...
