"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class Pr0grammStaticIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class Pr0grammIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
