"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RbgTumIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class RbgTumCourseIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
