version: "3.9"

services:
  tubesubs:
    container_name: "tubesubs"
    image: ghcr.io/martokk/tubesubs:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/tubesubs/data:/tubesubs/data
      - ./app:/app
    ports:
      - "5000:5000"
