"""
This type stub file was generated by pyright.
"""

class FileStore:
    ...


class MemoryFileStore(FileStore):
    file_cls = ...
    def __init__(self, file_cls=...) -> None:
        ...
    
    def __contains__(self, k): # -> bool:
        ...
    
    def keys(self): # -> list[Unknown]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def as_dict(self): # -> Generator[Unknown, None, None]:
        ...
    
    def remove(self, uri): # -> None:
        ...
    
    def unique_filename(self, filename, uri=...): # -> str:
        ...
    
    def add(self, value, replace=...): # -> BaseFile:
        ...
    
    def by_uri(self, uri): # -> None:
        ...
    
    def by_filename(self, filename): # -> None:
        ...
    
    def __getitem__(self, uri): # -> None:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    


