"""add tag.color

Revision ID: 11e142e18c14
Revises: c2b00a0ce177
Create Date: 2023-08-03 13:27:15.838609

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "11e142e18c14"
down_revision = "c2b00a0ce177"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channeltaglink", schema=None) as batch_op:
        batch_op.drop_constraint("fk_channeltaglink_tag_id_filter", type_="foreignkey")
        batch_op.create_foreign_key(None, "tag", ["tag_id"], ["id"])

    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color", sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default="#000000"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("color")

    with op.batch_alter_table("channeltaglink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key("fk_channeltaglink_tag_id_filter", "filter", ["tag_id"], ["id"])

    # ### end Alembic commands ###
