"""add channels.is_hidden

Revision ID: 2475b17c93ad
Revises: f66306890361
Create Date: 2023-08-01 21:50:57.422720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "2475b17c93ad"
down_revision = "f66306890361"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_hidden", sa.Boolean(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_hidden_channels", sa.Boolean(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filter", schema=None) as batch_op:
        batch_op.drop_column("show_hidden_channels")

    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.drop_column("is_hidden")

    # ### end Alembic commands ###
