"""add subscription.max_videos_per_fetch

Revision ID: 34edd7b98a76
Revises: d306d0ab74fd
Create Date: 2023-08-09 23:38:34.618321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "34edd7b98a76"
down_revision = "d306d0ab74fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("max_videos_per_fetch", sa.Integer(), nullable=False, server_default="50")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.drop_column("max_videos_per_fetch")

    # ### end Alembic commands ###
