"""add channel.is_subscribed

Revision ID: 8218d280afd3
Revises: 86b20b1aeb38
Create Date: 2023-08-08 01:38:43.554756

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "8218d280afd3"
down_revision = "86b20b1aeb38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_subscribed", sa.Boolean(), nullable=False, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.drop_column("is_subscribed")

    # ### end Alembic commands ###
