"""added Video.is_read

Revision ID: ce8642782d79
Revises: a2b7596775de
Create Date: 2023-07-30 21:19:17.290026

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "ce8642782d79"
down_revision = "a2b7596775de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video", sa.Column("is_read", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "is_read")
    # ### end Alembic commands ###
