"""added Filter.reverse_order

Revision ID: d6d0658d2a12
Revises: ce8642782d79
Create Date: 2023-07-31 00:34:04.779726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "d6d0658d2a12"
down_revision = "ce8642782d79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "filter", sa.Column("reverse_order", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filter", "reverse_order")
    # ### end Alembic commands ###
