"""
This type stub file was generated by pyright.
"""

__all__ = ['OrderedSet']
class OrderedSet(MutableSet):
    def __init__(self, iterable=...) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def add(self, key): # -> None:
        ...
    
    def discard(self, key): # -> None:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    
    def __reversed__(self): # -> Generator[Unknown, None, None]:
        ...
    
    def pop(self, last=...):
        ...
    
    def __repr__(self): # -> LiteralString | str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


