"""
This type stub file was generated by pyright.
"""

import brotlicffi as brotli
import certifi
import mutagen
import secretstorage
import sqlite3
import websockets
import xattr
from . import Cryptodome

"""Imports all optional dependencies for the project.
An attribute "_yt_dlp__identifier" may be inserted into the module if it uses an ambiguous namespace"""
secretstorage = ...
_SECRETSTORAGE_UNAVAILABLE_REASON = ...
all_dependencies = ...
available_dependencies = ...
Cryptodome_AES = ...
__all__ = ['all_dependencies', 'available_dependencies', *all_dependencies.keys()]
