"""
This type stub file was generated by pyright.
"""

import Cryptodome as _parent
from Cryptodome import __version__
from Cryptodome.Cipher import AES
from Cryptodome.PublicKey import RSA
from Crypto import __version__
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA

__version__ = ...
RSA = ...
if _parent.__name__ == 'Cryptodome':
    ...
else:
    ...
_yt_dlp__identifier = ...
if AES and _yt_dlp__identifier == 'Crypto':
    ...
