"""
This type stub file was generated by pyright.
"""

import importlib
import importlib.abc
from .compat import functools

PACKAGE_NAME = ...
COMPAT_PACKAGE_NAME = ...
class PluginLoader(importlib.abc.Loader):
    """Dummy loader for virtual namespace packages"""
    def exec_module(self, module): # -> None:
        ...



@functools.cache
def dirs_in_zip(archive): # -> set[Path] | set[Unknown]:
    ...

class PluginFinder(importlib.abc.MetaPathFinder):
    """
    This class provides one or multiple namespace packages.
    It searches in sys.path and yt-dlp config folders for
    the existing subdirectories from which the modules can be imported
    """
    def __init__(self, *packages) -> None:
        ...

    def search_locations(self, fullname): # -> Generator[Unknown, Any, None]:
        ...

    def find_spec(self, fullname, path=..., target=...): # -> ModuleSpec | None:
        ...

    def invalidate_caches(self): # -> None:
        ...



def directories(): # -> list[str] | None:
    ...

def iter_modules(subpackage): # -> Generator[ModuleInfo, Unknown, None]:
    ...

def load_module(module, module_name, suffix): # -> _GetMembersReturn:
    ...

def load_plugins(name, suffix): # -> dict[Unknown, Unknown]:
    ...

__all__ = ['directories', 'load_plugins', 'PACKAGE_NAME', 'COMPAT_PACKAGE_NAME']
