"""
This type stub file was generated by pyright.
"""

def simple_dict2str(d): # -> LiteralString:
    ...

_serializer = ...
class ObjectFactory:
    """
    Get object from cache or create new object.
    """
    def __init__(self, cls) -> None:
        ...
    
    def __getitem__(self, k):
        ...
    
    def invalidate(self, k):
        ...
    


