"""
This type stub file was generated by pyright.
"""

from smtplib import SMTP, SMTP_SSL, _have_ssl

__all__ = ['SMTPClientWithResponse', 'SMTPClientWithResponse_SSL']
logger = ...
class SMTPClientWithResponse(SMTP):
    def __init__(self, parent, **kwargs) -> None:
        ...
    
    def initialize(self): # -> None:
        ...
    
    def quit(self): # -> None:
        """Closes the connection to the email server."""
        ...
    
    def sendmail(self, from_addr, to_addrs, msg, mail_options=..., rcpt_options=...): # -> None:
        ...
    


if _have_ssl:
    class SMTPClientWithResponse_SSL(SMTP_SSL, SMTPClientWithResponse):
        def __init__(self, **kw) -> None:
            ...
        
        def quit(self): # -> None:
            """Closes the connection to the email server."""
            ...
        
        def sendmail(self, *args, **kw): # -> None:
            ...
        
    
    
else:
    class SMTPClientWithResponse_SSL:
        def __init__(self, *args, **kwargs) -> None:
            ...
        
    
    
