"""
This type stub file was generated by pyright.
"""

class SMTPConnectNetworkError(IOError):
    """Network error during connection establishment."""
    @classmethod
    def from_ioerror(cls, exc): # -> Self@SMTPConnectNetworkError:
        ...
